name: CI

on:
   push:
      branches:
         - master
   pull_request:

jobs:
   eslint:
      name: Eslint
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@v2
           with:
              node-version: '18.4.0'
              cache: npm
              cache-dependency-path: package-lock.json
         - run: npm install
         - run: npm run check:eslint

   prettier:
      name: Prettier
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@v2
           with:
              node-version: '18.4.0'
              cache: npm
              cache-dependency-path: package-lock.json
         - run: npm install
         - run: npm run check:prettier

   typescript:
      name: TypeScript
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@v2
           with:
              node-version: '18.4.0'
              cache: npm
              cache-dependency-path: package-lock.json
         - run: npm install
         - run: npm run check:typescript

   unit_tests:
      name: Unit tests
      runs-on: ubuntu-latest
      needs: [prettier, typescript, eslint]
      steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@v2
           with:
              node-version: '18.4.0'
              cache: npm
              cache-dependency-path: package-lock.json
         - run: npm install
         - run: npm run test

   merge_dependabot:
      name: 'Merge (Dependabot)'
      needs: [unit_tests]
      runs-on: ubuntu-latest
      permissions:
         pull-requests: write
      if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
      steps:
         - run: gh pr merge --auto --merge "$PR_URL"
           env:
              PR_URL: ${{github.event.pull_request.html_url}}
              GITHUB_TOKEN: ${{secrets.CUSTOM_GITHUB_TOKEN}}
